// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { completeBookDocumentUpload, createBook, createBookDocumentPresign, deleteBookById, deleteBookDocumentById, downloadBookDocument, getBookById, getBookDocumentById, listBookDocuments, listBooks, lookupBookByIsbn, type Options, searchBooks, updateBook } from '../sdk.gen';
import type { CompleteBookDocumentUploadData, CompleteBookDocumentUploadError, CompleteBookDocumentUploadResponse, CreateBookData, CreateBookDocumentPresignData, CreateBookDocumentPresignError, CreateBookDocumentPresignResponse, CreateBookError, CreateBookResponse, DeleteBookByIdData, DeleteBookByIdError, DeleteBookByIdResponse, DeleteBookDocumentByIdData, DeleteBookDocumentByIdError, DeleteBookDocumentByIdResponse, DownloadBookDocumentData, DownloadBookDocumentError, GetBookByIdData, GetBookByIdError, GetBookByIdResponse, GetBookDocumentByIdData, GetBookDocumentByIdError, GetBookDocumentByIdResponse, ListBookDocumentsData, ListBookDocumentsError, ListBookDocumentsResponse, ListBooksData, ListBooksResponse, LookupBookByIsbnData, LookupBookByIsbnError, LookupBookByIsbnResponse, SearchBooksData, SearchBooksResponse, UpdateBookData, UpdateBookError, UpdateBookResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listBooksQueryKey = (options?: Options<ListBooksData>) => createQueryKey('listBooks', options);

/**
 * List books
 */
export const listBooksOptions = (options?: Options<ListBooksData>) => queryOptions<ListBooksResponse, DefaultError, ListBooksResponse, ReturnType<typeof listBooksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBooks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBooksQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listBooksInfiniteQueryKey = (options?: Options<ListBooksData>): QueryKey<Options<ListBooksData>> => createQueryKey('listBooks', options, true);

/**
 * List books
 */
export const listBooksInfiniteOptions = (options?: Options<ListBooksData>) => infiniteQueryOptions<ListBooksResponse, DefaultError, InfiniteData<ListBooksResponse>, QueryKey<Options<ListBooksData>>, number | Pick<QueryKey<Options<ListBooksData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListBooksData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listBooks({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBooksInfiniteQueryKey(options)
});

/**
 * Create a new book
 */
export const createBookMutation = (options?: Partial<Options<CreateBookData>>): UseMutationOptions<CreateBookResponse, CreateBookError, Options<CreateBookData>> => {
    const mutationOptions: UseMutationOptions<CreateBookResponse, CreateBookError, Options<CreateBookData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBook({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const searchBooksQueryKey = (options: Options<SearchBooksData>) => createQueryKey('searchBooks', options);

/**
 * Search books by title or author
 */
export const searchBooksOptions = (options: Options<SearchBooksData>) => queryOptions<SearchBooksResponse, DefaultError, SearchBooksResponse, ReturnType<typeof searchBooksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchBooks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchBooksQueryKey(options)
});

export const searchBooksInfiniteQueryKey = (options: Options<SearchBooksData>): QueryKey<Options<SearchBooksData>> => createQueryKey('searchBooks', options, true);

/**
 * Search books by title or author
 */
export const searchBooksInfiniteOptions = (options: Options<SearchBooksData>) => infiniteQueryOptions<SearchBooksResponse, DefaultError, InfiniteData<SearchBooksResponse>, QueryKey<Options<SearchBooksData>>, number | Pick<QueryKey<Options<SearchBooksData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<SearchBooksData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await searchBooks({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchBooksInfiniteQueryKey(options)
});

export const lookupBookByIsbnQueryKey = (options: Options<LookupBookByIsbnData>) => createQueryKey('lookupBookByIsbn', options);

/**
 * Lookup book metadata by ISBN from OpenLibrary
 */
export const lookupBookByIsbnOptions = (options: Options<LookupBookByIsbnData>) => queryOptions<LookupBookByIsbnResponse, LookupBookByIsbnError, LookupBookByIsbnResponse, ReturnType<typeof lookupBookByIsbnQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lookupBookByIsbn({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lookupBookByIsbnQueryKey(options)
});

/**
 * Delete book by id
 */
export const deleteBookByIdMutation = (options?: Partial<Options<DeleteBookByIdData>>): UseMutationOptions<DeleteBookByIdResponse, DeleteBookByIdError, Options<DeleteBookByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteBookByIdResponse, DeleteBookByIdError, Options<DeleteBookByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteBookById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBookByIdQueryKey = (options: Options<GetBookByIdData>) => createQueryKey('getBookById', options);

/**
 * Get book by id
 */
export const getBookByIdOptions = (options: Options<GetBookByIdData>) => queryOptions<GetBookByIdResponse, GetBookByIdError, GetBookByIdResponse, ReturnType<typeof getBookByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBookById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBookByIdQueryKey(options)
});

/**
 * Replace a book by id
 */
export const updateBookMutation = (options?: Partial<Options<UpdateBookData>>): UseMutationOptions<UpdateBookResponse, UpdateBookError, Options<UpdateBookData>> => {
    const mutationOptions: UseMutationOptions<UpdateBookResponse, UpdateBookError, Options<UpdateBookData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBook({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBookDocumentsQueryKey = (options: Options<ListBookDocumentsData>) => createQueryKey('listBookDocuments', options);

/**
 * List documents for a book
 */
export const listBookDocumentsOptions = (options: Options<ListBookDocumentsData>) => queryOptions<ListBookDocumentsResponse, ListBookDocumentsError, ListBookDocumentsResponse, ReturnType<typeof listBookDocumentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBookDocuments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBookDocumentsQueryKey(options)
});

export const listBookDocumentsInfiniteQueryKey = (options: Options<ListBookDocumentsData>): QueryKey<Options<ListBookDocumentsData>> => createQueryKey('listBookDocuments', options, true);

/**
 * List documents for a book
 */
export const listBookDocumentsInfiniteOptions = (options: Options<ListBookDocumentsData>) => infiniteQueryOptions<ListBookDocumentsResponse, ListBookDocumentsError, InfiniteData<ListBookDocumentsResponse>, QueryKey<Options<ListBookDocumentsData>>, number | Pick<QueryKey<Options<ListBookDocumentsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListBookDocumentsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listBookDocuments({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBookDocumentsInfiniteQueryKey(options)
});

/**
 * Create a presigned upload URL for a document
 *
 * Only authenticated uploaders can request a presigned URL.
 */
export const createBookDocumentPresignMutation = (options?: Partial<Options<CreateBookDocumentPresignData>>): UseMutationOptions<CreateBookDocumentPresignResponse, CreateBookDocumentPresignError, Options<CreateBookDocumentPresignData>> => {
    const mutationOptions: UseMutationOptions<CreateBookDocumentPresignResponse, CreateBookDocumentPresignError, Options<CreateBookDocumentPresignData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBookDocumentPresign({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a document
 *
 * Only the uploader or an admin can delete documents.
 */
export const deleteBookDocumentByIdMutation = (options?: Partial<Options<DeleteBookDocumentByIdData>>): UseMutationOptions<DeleteBookDocumentByIdResponse, DeleteBookDocumentByIdError, Options<DeleteBookDocumentByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteBookDocumentByIdResponse, DeleteBookDocumentByIdError, Options<DeleteBookDocumentByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteBookDocumentById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBookDocumentByIdQueryKey = (options: Options<GetBookDocumentByIdData>) => createQueryKey('getBookDocumentById', options);

/**
 * Get document metadata
 */
export const getBookDocumentByIdOptions = (options: Options<GetBookDocumentByIdData>) => queryOptions<GetBookDocumentByIdResponse, GetBookDocumentByIdError, GetBookDocumentByIdResponse, ReturnType<typeof getBookDocumentByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBookDocumentById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBookDocumentByIdQueryKey(options)
});

/**
 * Confirm document upload and persist metadata
 *
 * Completes the upload after the file is stored in R2.
 */
export const completeBookDocumentUploadMutation = (options?: Partial<Options<CompleteBookDocumentUploadData>>): UseMutationOptions<CompleteBookDocumentUploadResponse, CompleteBookDocumentUploadError, Options<CompleteBookDocumentUploadData>> => {
    const mutationOptions: UseMutationOptions<CompleteBookDocumentUploadResponse, CompleteBookDocumentUploadError, Options<CompleteBookDocumentUploadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await completeBookDocumentUpload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const downloadBookDocumentQueryKey = (options: Options<DownloadBookDocumentData>) => createQueryKey('downloadBookDocument', options);

/**
 * Download a document
 *
 * Redirects to the public R2 object URL.
 */
export const downloadBookDocumentOptions = (options: Options<DownloadBookDocumentData>) => queryOptions<unknown, DownloadBookDocumentError, unknown, ReturnType<typeof downloadBookDocumentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await downloadBookDocument({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: downloadBookDocumentQueryKey(options)
});
