// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID            int64              `json:"id"`
	Title         string             `json:"title"`
	Author        string             `json:"author"`
	PublishedYear int32              `json:"published_year"`
	Isbn          string             `json:"isbn"`
	Genre         *string            `json:"genre"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
