// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/url"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Book defines model for Book.
type Book struct {
	Author        string  `json:"author"`
	Genre         *string `json:"genre,omitempty"`
	Id            int64   `json:"id"`
	Isbn          string  `json:"isbn"`
	PublishedYear string  `json:"publishedYear"`
	Title         string  `json:"title"`
}

// BookCreate defines model for BookCreate.
type BookCreate struct {
	Author        string  `json:"author"`
	Genre         *string `json:"genre,omitempty"`
	Isbn          string  `json:"isbn"`
	PublishedYear string  `json:"publishedYear"`
	Title         string  `json:"title"`
}

// BookList defines model for BookList.
type BookList struct {
	Items []Book `json:"items"`
	Total int64  `json:"total"`
}

// BookUpdate defines model for BookUpdate.
type BookUpdate struct {
	Author        string  `json:"author"`
	Genre         *string `json:"genre,omitempty"`
	Isbn          string  `json:"isbn"`
	PublishedYear string  `json:"publishedYear"`
	Title         string  `json:"title"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// BookID defines model for BookID.
type BookID = int64

// ListBooksParams defines parameters for ListBooks.
type ListBooksParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchBooksParams defines parameters for SearchBooks.
type SearchBooksParams struct {
	Q      string `form:"q" json:"q"`
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = BookCreate

// UpdateBookJSONRequestBody defines body for UpdateBook for application/json ContentType.
type UpdateBookJSONRequestBody = BookUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List books
	// (GET /books)
	ListBooks(c *fiber.Ctx, params ListBooksParams) error
	// Create a new book
	// (POST /books)
	CreateBook(c *fiber.Ctx) error
	// Search books by title or author
	// (GET /books/search)
	SearchBooks(c *fiber.Ctx, params SearchBooksParams) error
	// Delete book by id
	// (DELETE /books/{bookID})
	DeleteBookByID(c *fiber.Ctx, bookID BookID) error
	// Get book by id
	// (GET /books/{bookID})
	GetBookByID(c *fiber.Ctx, bookID BookID) error
	// Replace a book by id
	// (PUT /books/{bookID})
	UpdateBook(c *fiber.Ctx, bookID BookID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListBooks operation middleware
func (siw *ServerInterfaceWrapper) ListBooks(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBooksParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.ListBooks(c, params)
}

// CreateBook operation middleware
func (siw *ServerInterfaceWrapper) CreateBook(c *fiber.Ctx) error {

	return siw.Handler.CreateBook(c)
}

// SearchBooks operation middleware
func (siw *ServerInterfaceWrapper) SearchBooks(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchBooksParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument q is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "q", query, &params.Q)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter q: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.SearchBooks(c, params)
}

// DeleteBookByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.DeleteBookByID(c, bookID)
}

// GetBookByID operation middleware
func (siw *ServerInterfaceWrapper) GetBookByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.GetBookByID(c, bookID)
}

// UpdateBook operation middleware
func (siw *ServerInterfaceWrapper) UpdateBook(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.UpdateBook(c, bookID)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/books", wrapper.ListBooks)

	router.Post(options.BaseURL+"/books", wrapper.CreateBook)

	router.Get(options.BaseURL+"/books/search", wrapper.SearchBooks)

	router.Delete(options.BaseURL+"/books/:bookID", wrapper.DeleteBookByID)

	router.Get(options.BaseURL+"/books/:bookID", wrapper.GetBookByID)

	router.Put(options.BaseURL+"/books/:bookID", wrapper.UpdateBook)

}

type ListBooksRequestObject struct {
	Params ListBooksParams
}

type ListBooksResponseObject interface {
	VisitListBooksResponse(ctx *fiber.Ctx) error
}

type ListBooks200JSONResponse BookList

func (response ListBooks200JSONResponse) VisitListBooksResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateBookRequestObject struct {
	Body *CreateBookJSONRequestBody
}

type CreateBookResponseObject interface {
	VisitCreateBookResponse(ctx *fiber.Ctx) error
}

type CreateBook201JSONResponse Book

func (response CreateBook201JSONResponse) VisitCreateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateBook422JSONResponse Problem

func (response CreateBook422JSONResponse) VisitCreateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type SearchBooksRequestObject struct {
	Params SearchBooksParams
}

type SearchBooksResponseObject interface {
	VisitSearchBooksResponse(ctx *fiber.Ctx) error
}

type SearchBooks200JSONResponse BookList

func (response SearchBooks200JSONResponse) VisitSearchBooksResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type DeleteBookByIDRequestObject struct {
	BookID BookID `json:"bookID"`
}

type DeleteBookByIDResponseObject interface {
	VisitDeleteBookByIDResponse(ctx *fiber.Ctx) error
}

type DeleteBookByID204Response struct {
}

func (response DeleteBookByID204Response) VisitDeleteBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteBookByID404JSONResponse Problem

func (response DeleteBookByID404JSONResponse) VisitDeleteBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetBookByIDRequestObject struct {
	BookID BookID `json:"bookID"`
}

type GetBookByIDResponseObject interface {
	VisitGetBookByIDResponse(ctx *fiber.Ctx) error
}

type GetBookByID200JSONResponse Book

func (response GetBookByID200JSONResponse) VisitGetBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetBookByID404JSONResponse Problem

func (response GetBookByID404JSONResponse) VisitGetBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateBookRequestObject struct {
	BookID BookID `json:"bookID"`
	Body   *UpdateBookJSONRequestBody
}

type UpdateBookResponseObject interface {
	VisitUpdateBookResponse(ctx *fiber.Ctx) error
}

type UpdateBook200JSONResponse Book

func (response UpdateBook200JSONResponse) VisitUpdateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateBook404JSONResponse Problem

func (response UpdateBook404JSONResponse) VisitUpdateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateBook422JSONResponse Problem

func (response UpdateBook422JSONResponse) VisitUpdateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List books
	// (GET /books)
	ListBooks(ctx context.Context, request ListBooksRequestObject) (ListBooksResponseObject, error)
	// Create a new book
	// (POST /books)
	CreateBook(ctx context.Context, request CreateBookRequestObject) (CreateBookResponseObject, error)
	// Search books by title or author
	// (GET /books/search)
	SearchBooks(ctx context.Context, request SearchBooksRequestObject) (SearchBooksResponseObject, error)
	// Delete book by id
	// (DELETE /books/{bookID})
	DeleteBookByID(ctx context.Context, request DeleteBookByIDRequestObject) (DeleteBookByIDResponseObject, error)
	// Get book by id
	// (GET /books/{bookID})
	GetBookByID(ctx context.Context, request GetBookByIDRequestObject) (GetBookByIDResponseObject, error)
	// Replace a book by id
	// (PUT /books/{bookID})
	UpdateBook(ctx context.Context, request UpdateBookRequestObject) (UpdateBookResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListBooks operation middleware
func (sh *strictHandler) ListBooks(ctx *fiber.Ctx, params ListBooksParams) error {
	var request ListBooksRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListBooks(ctx.UserContext(), request.(ListBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListBooksResponseObject); ok {
		if err := validResponse.VisitListBooksResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateBook operation middleware
func (sh *strictHandler) CreateBook(ctx *fiber.Ctx) error {
	var request CreateBookRequestObject

	var body CreateBookJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBook(ctx.UserContext(), request.(CreateBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateBookResponseObject); ok {
		if err := validResponse.VisitCreateBookResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchBooks operation middleware
func (sh *strictHandler) SearchBooks(ctx *fiber.Ctx, params SearchBooksParams) error {
	var request SearchBooksRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SearchBooks(ctx.UserContext(), request.(SearchBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchBooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(SearchBooksResponseObject); ok {
		if err := validResponse.VisitSearchBooksResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBookByID operation middleware
func (sh *strictHandler) DeleteBookByID(ctx *fiber.Ctx, bookID BookID) error {
	var request DeleteBookByIDRequestObject

	request.BookID = bookID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBookByID(ctx.UserContext(), request.(DeleteBookByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBookByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteBookByIDResponseObject); ok {
		if err := validResponse.VisitDeleteBookByIDResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBookByID operation middleware
func (sh *strictHandler) GetBookByID(ctx *fiber.Ctx, bookID BookID) error {
	var request GetBookByIDRequestObject

	request.BookID = bookID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetBookByID(ctx.UserContext(), request.(GetBookByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBookByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetBookByIDResponseObject); ok {
		if err := validResponse.VisitGetBookByIDResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateBook operation middleware
func (sh *strictHandler) UpdateBook(ctx *fiber.Ctx, bookID BookID) error {
	var request UpdateBookRequestObject

	request.BookID = bookID

	var body UpdateBookJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBook(ctx.UserContext(), request.(UpdateBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateBookResponseObject); ok {
		if err := validResponse.VisitUpdateBookResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
