// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ContentType.
const (
	ApplicationepubZip ContentType = "application/epub+zip"
	Applicationpdf     ContentType = "application/pdf"
)

// Defines values for DocumentPresignResponseUploadMethod.
const (
	PUT DocumentPresignResponseUploadMethod = "PUT"
)

// Defines values for UploadStatus.
const (
	Failed     UploadStatus = "failed"
	Pending    UploadStatus = "pending"
	Processing UploadStatus = "processing"
	Ready      UploadStatus = "ready"
	Uploaded   UploadStatus = "uploaded"
)

// Book defines model for Book.
type Book struct {
	Author        string  `json:"author"`
	Genre         *string `json:"genre,omitempty"`
	Id            int64   `json:"id"`
	Isbn          string  `json:"isbn"`
	PublishedYear string  `json:"publishedYear"`
	Title         string  `json:"title"`
}

// BookCreate defines model for BookCreate.
type BookCreate struct {
	Author        string  `json:"author"`
	Genre         *string `json:"genre,omitempty"`
	Isbn          string  `json:"isbn"`
	PublishedYear string  `json:"publishedYear"`
	Title         string  `json:"title"`
}

// BookList defines model for BookList.
type BookList struct {
	Items []Book `json:"items"`
	Total int64  `json:"total"`
}

// BookUpdate defines model for BookUpdate.
type BookUpdate struct {
	Author        string  `json:"author"`
	Genre         *string `json:"genre,omitempty"`
	Isbn          string  `json:"isbn"`
	PublishedYear string  `json:"publishedYear"`
	Title         string  `json:"title"`
}

// ContentType defines model for ContentType.
type ContentType string

// Document defines model for Document.
type Document struct {
	BookID int64 `json:"bookID"`

	// ChecksumSha256Hex SHA-256 checksum as 64 lowercase hex chars
	ChecksumSha256Hex *string      `json:"checksumSha256Hex,omitempty"`
	ContentType       ContentType  `json:"contentType"`
	CreatedAt         time.Time    `json:"createdAt"`
	Filename          string       `json:"filename"`
	Id                int64        `json:"id"`
	ObjectKey         *string      `json:"objectKey,omitempty"`
	SizeBytes         int64        `json:"sizeBytes"`
	Status            UploadStatus `json:"status"`
	UpdatedAt         time.Time    `json:"updatedAt"`
}

// DocumentList defines model for DocumentList.
type DocumentList struct {
	Items []Document `json:"items"`
	Total int64      `json:"total"`
}

// DocumentPresignResponse defines model for DocumentPresignResponse.
type DocumentPresignResponse struct {
	Document     Document                            `json:"document"`
	ExpiresAt    time.Time                           `json:"expiresAt"`
	UploadMethod DocumentPresignResponseUploadMethod `json:"uploadMethod"`
	UploadUrl    string                              `json:"uploadUrl"`
}

// DocumentPresignResponseUploadMethod defines model for DocumentPresignResponse.UploadMethod.
type DocumentPresignResponseUploadMethod string

// DocumentUploadRequest defines model for DocumentUploadRequest.
type DocumentUploadRequest struct {
	// ChecksumSha256Hex SHA-256 checksum as 64 lowercase hex chars
	ChecksumSha256Hex string             `json:"checksumSha256Hex"`
	ContentType       ContentType        `json:"contentType"`
	Filename          string             `json:"filename"`
	Metadata          *map[string]string `json:"metadata,omitempty"`
	SizeBytes         int64              `json:"sizeBytes"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// UploadStatus defines model for UploadStatus.
type UploadStatus string

// BookID defines model for BookID.
type BookID = int64

// DocumentID defines model for DocumentID.
type DocumentID = int64

// ListBooksParams defines parameters for ListBooks.
type ListBooksParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchBooksParams defines parameters for SearchBooks.
type SearchBooksParams struct {
	Q      string `form:"q" json:"q"`
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListBookDocumentsParams defines parameters for ListBookDocuments.
type ListBookDocumentsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = BookCreate

// UpdateBookJSONRequestBody defines body for UpdateBook for application/json ContentType.
type UpdateBookJSONRequestBody = BookUpdate

// CreateBookDocumentPresignJSONRequestBody defines body for CreateBookDocumentPresign for application/json ContentType.
type CreateBookDocumentPresignJSONRequestBody = DocumentUploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List books
	// (GET /books)
	ListBooks(c *fiber.Ctx, params ListBooksParams) error
	// Create a new book
	// (POST /books)
	CreateBook(c *fiber.Ctx) error
	// Search books by title or author
	// (GET /books/search)
	SearchBooks(c *fiber.Ctx, params SearchBooksParams) error
	// Delete book by id
	// (DELETE /books/{bookID})
	DeleteBookByID(c *fiber.Ctx, bookID BookID) error
	// Get book by id
	// (GET /books/{bookID})
	GetBookByID(c *fiber.Ctx, bookID BookID) error
	// Replace a book by id
	// (PUT /books/{bookID})
	UpdateBook(c *fiber.Ctx, bookID BookID) error
	// List documents for a book
	// (GET /books/{bookID}/documents)
	ListBookDocuments(c *fiber.Ctx, bookID BookID, params ListBookDocumentsParams) error
	// Create a presigned upload URL for a document
	// (POST /books/{bookID}/documents/presign)
	CreateBookDocumentPresign(c *fiber.Ctx, bookID BookID) error
	// Delete a document
	// (DELETE /books/{bookID}/documents/{documentID})
	DeleteBookDocumentByID(c *fiber.Ctx, bookID BookID, documentID DocumentID) error
	// Get document metadata
	// (GET /books/{bookID}/documents/{documentID})
	GetBookDocumentByID(c *fiber.Ctx, bookID BookID, documentID DocumentID) error
	// Confirm document upload and persist metadata
	// (POST /books/{bookID}/documents/{documentID}/complete)
	CompleteBookDocumentUpload(c *fiber.Ctx, bookID BookID, documentID DocumentID) error
	// Download a document
	// (GET /books/{bookID}/documents/{documentID}/download)
	DownloadBookDocument(c *fiber.Ctx, bookID BookID, documentID DocumentID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListBooks operation middleware
func (siw *ServerInterfaceWrapper) ListBooks(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBooksParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.ListBooks(c, params)
}

// CreateBook operation middleware
func (siw *ServerInterfaceWrapper) CreateBook(c *fiber.Ctx) error {

	return siw.Handler.CreateBook(c)
}

// SearchBooks operation middleware
func (siw *ServerInterfaceWrapper) SearchBooks(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchBooksParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument q is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "q", query, &params.Q)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter q: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.SearchBooks(c, params)
}

// DeleteBookByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.DeleteBookByID(c, bookID)
}

// GetBookByID operation middleware
func (siw *ServerInterfaceWrapper) GetBookByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.GetBookByID(c, bookID)
}

// UpdateBook operation middleware
func (siw *ServerInterfaceWrapper) UpdateBook(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.UpdateBook(c, bookID)
}

// ListBookDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListBookDocuments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookDocumentsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.ListBookDocuments(c, bookID, params)
}

// CreateBookDocumentPresign operation middleware
func (siw *ServerInterfaceWrapper) CreateBookDocumentPresign(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	return siw.Handler.CreateBookDocumentPresign(c, bookID)
}

// DeleteBookDocumentByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookDocumentByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	// ------------- Path parameter "documentID" -------------
	var documentID DocumentID

	err = runtime.BindStyledParameterWithOptions("simple", "documentID", c.Params("documentID"), &documentID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter documentID: %w", err).Error())
	}

	return siw.Handler.DeleteBookDocumentByID(c, bookID, documentID)
}

// GetBookDocumentByID operation middleware
func (siw *ServerInterfaceWrapper) GetBookDocumentByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	// ------------- Path parameter "documentID" -------------
	var documentID DocumentID

	err = runtime.BindStyledParameterWithOptions("simple", "documentID", c.Params("documentID"), &documentID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter documentID: %w", err).Error())
	}

	return siw.Handler.GetBookDocumentByID(c, bookID, documentID)
}

// CompleteBookDocumentUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteBookDocumentUpload(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	// ------------- Path parameter "documentID" -------------
	var documentID DocumentID

	err = runtime.BindStyledParameterWithOptions("simple", "documentID", c.Params("documentID"), &documentID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter documentID: %w", err).Error())
	}

	return siw.Handler.CompleteBookDocumentUpload(c, bookID, documentID)
}

// DownloadBookDocument operation middleware
func (siw *ServerInterfaceWrapper) DownloadBookDocument(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "bookID" -------------
	var bookID BookID

	err = runtime.BindStyledParameterWithOptions("simple", "bookID", c.Params("bookID"), &bookID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter bookID: %w", err).Error())
	}

	// ------------- Path parameter "documentID" -------------
	var documentID DocumentID

	err = runtime.BindStyledParameterWithOptions("simple", "documentID", c.Params("documentID"), &documentID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter documentID: %w", err).Error())
	}

	return siw.Handler.DownloadBookDocument(c, bookID, documentID)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/books", wrapper.ListBooks)

	router.Post(options.BaseURL+"/books", wrapper.CreateBook)

	router.Get(options.BaseURL+"/books/search", wrapper.SearchBooks)

	router.Delete(options.BaseURL+"/books/:bookID", wrapper.DeleteBookByID)

	router.Get(options.BaseURL+"/books/:bookID", wrapper.GetBookByID)

	router.Put(options.BaseURL+"/books/:bookID", wrapper.UpdateBook)

	router.Get(options.BaseURL+"/books/:bookID/documents", wrapper.ListBookDocuments)

	router.Post(options.BaseURL+"/books/:bookID/documents/presign", wrapper.CreateBookDocumentPresign)

	router.Delete(options.BaseURL+"/books/:bookID/documents/:documentID", wrapper.DeleteBookDocumentByID)

	router.Get(options.BaseURL+"/books/:bookID/documents/:documentID", wrapper.GetBookDocumentByID)

	router.Post(options.BaseURL+"/books/:bookID/documents/:documentID/complete", wrapper.CompleteBookDocumentUpload)

	router.Get(options.BaseURL+"/books/:bookID/documents/:documentID/download", wrapper.DownloadBookDocument)

}

type ListBooksRequestObject struct {
	Params ListBooksParams
}

type ListBooksResponseObject interface {
	VisitListBooksResponse(ctx *fiber.Ctx) error
}

type ListBooks200JSONResponse BookList

func (response ListBooks200JSONResponse) VisitListBooksResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreateBookRequestObject struct {
	Body *CreateBookJSONRequestBody
}

type CreateBookResponseObject interface {
	VisitCreateBookResponse(ctx *fiber.Ctx) error
}

type CreateBook201JSONResponse Book

func (response CreateBook201JSONResponse) VisitCreateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateBook422JSONResponse Problem

func (response CreateBook422JSONResponse) VisitCreateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type SearchBooksRequestObject struct {
	Params SearchBooksParams
}

type SearchBooksResponseObject interface {
	VisitSearchBooksResponse(ctx *fiber.Ctx) error
}

type SearchBooks200JSONResponse BookList

func (response SearchBooks200JSONResponse) VisitSearchBooksResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type DeleteBookByIDRequestObject struct {
	BookID BookID `json:"bookID"`
}

type DeleteBookByIDResponseObject interface {
	VisitDeleteBookByIDResponse(ctx *fiber.Ctx) error
}

type DeleteBookByID204Response struct {
}

func (response DeleteBookByID204Response) VisitDeleteBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteBookByID404JSONResponse Problem

func (response DeleteBookByID404JSONResponse) VisitDeleteBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetBookByIDRequestObject struct {
	BookID BookID `json:"bookID"`
}

type GetBookByIDResponseObject interface {
	VisitGetBookByIDResponse(ctx *fiber.Ctx) error
}

type GetBookByID200JSONResponse Book

func (response GetBookByID200JSONResponse) VisitGetBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetBookByID404JSONResponse Problem

func (response GetBookByID404JSONResponse) VisitGetBookByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateBookRequestObject struct {
	BookID BookID `json:"bookID"`
	Body   *UpdateBookJSONRequestBody
}

type UpdateBookResponseObject interface {
	VisitUpdateBookResponse(ctx *fiber.Ctx) error
}

type UpdateBook200JSONResponse Book

func (response UpdateBook200JSONResponse) VisitUpdateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateBook404JSONResponse Problem

func (response UpdateBook404JSONResponse) VisitUpdateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateBook422JSONResponse Problem

func (response UpdateBook422JSONResponse) VisitUpdateBookResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type ListBookDocumentsRequestObject struct {
	BookID BookID `json:"bookID"`
	Params ListBookDocumentsParams
}

type ListBookDocumentsResponseObject interface {
	VisitListBookDocumentsResponse(ctx *fiber.Ctx) error
}

type ListBookDocuments200JSONResponse DocumentList

func (response ListBookDocuments200JSONResponse) VisitListBookDocumentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListBookDocuments404JSONResponse Problem

func (response ListBookDocuments404JSONResponse) VisitListBookDocumentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type CreateBookDocumentPresignRequestObject struct {
	BookID BookID `json:"bookID"`
	Body   *CreateBookDocumentPresignJSONRequestBody
}

type CreateBookDocumentPresignResponseObject interface {
	VisitCreateBookDocumentPresignResponse(ctx *fiber.Ctx) error
}

type CreateBookDocumentPresign201JSONResponse DocumentPresignResponse

func (response CreateBookDocumentPresign201JSONResponse) VisitCreateBookDocumentPresignResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateBookDocumentPresign404JSONResponse Problem

func (response CreateBookDocumentPresign404JSONResponse) VisitCreateBookDocumentPresignResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type CreateBookDocumentPresign422JSONResponse Problem

func (response CreateBookDocumentPresign422JSONResponse) VisitCreateBookDocumentPresignResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type DeleteBookDocumentByIDRequestObject struct {
	BookID     BookID     `json:"bookID"`
	DocumentID DocumentID `json:"documentID"`
}

type DeleteBookDocumentByIDResponseObject interface {
	VisitDeleteBookDocumentByIDResponse(ctx *fiber.Ctx) error
}

type DeleteBookDocumentByID204Response struct {
}

func (response DeleteBookDocumentByID204Response) VisitDeleteBookDocumentByIDResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteBookDocumentByID404JSONResponse Problem

func (response DeleteBookDocumentByID404JSONResponse) VisitDeleteBookDocumentByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetBookDocumentByIDRequestObject struct {
	BookID     BookID     `json:"bookID"`
	DocumentID DocumentID `json:"documentID"`
}

type GetBookDocumentByIDResponseObject interface {
	VisitGetBookDocumentByIDResponse(ctx *fiber.Ctx) error
}

type GetBookDocumentByID200JSONResponse Document

func (response GetBookDocumentByID200JSONResponse) VisitGetBookDocumentByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetBookDocumentByID404JSONResponse Problem

func (response GetBookDocumentByID404JSONResponse) VisitGetBookDocumentByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type CompleteBookDocumentUploadRequestObject struct {
	BookID     BookID     `json:"bookID"`
	DocumentID DocumentID `json:"documentID"`
}

type CompleteBookDocumentUploadResponseObject interface {
	VisitCompleteBookDocumentUploadResponse(ctx *fiber.Ctx) error
}

type CompleteBookDocumentUpload200JSONResponse Document

func (response CompleteBookDocumentUpload200JSONResponse) VisitCompleteBookDocumentUploadResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CompleteBookDocumentUpload404JSONResponse Problem

func (response CompleteBookDocumentUpload404JSONResponse) VisitCompleteBookDocumentUploadResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type CompleteBookDocumentUpload422JSONResponse Problem

func (response CompleteBookDocumentUpload422JSONResponse) VisitCompleteBookDocumentUploadResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type DownloadBookDocumentRequestObject struct {
	BookID     BookID     `json:"bookID"`
	DocumentID DocumentID `json:"documentID"`
}

type DownloadBookDocumentResponseObject interface {
	VisitDownloadBookDocumentResponse(ctx *fiber.Ctx) error
}

type DownloadBookDocument302ResponseHeaders struct {
	Location string
}

type DownloadBookDocument302Response struct {
	Headers DownloadBookDocument302ResponseHeaders
}

func (response DownloadBookDocument302Response) VisitDownloadBookDocumentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Location", fmt.Sprint(response.Headers.Location))
	ctx.Status(302)
	return nil
}

type DownloadBookDocument404JSONResponse Problem

func (response DownloadBookDocument404JSONResponse) VisitDownloadBookDocumentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List books
	// (GET /books)
	ListBooks(ctx context.Context, request ListBooksRequestObject) (ListBooksResponseObject, error)
	// Create a new book
	// (POST /books)
	CreateBook(ctx context.Context, request CreateBookRequestObject) (CreateBookResponseObject, error)
	// Search books by title or author
	// (GET /books/search)
	SearchBooks(ctx context.Context, request SearchBooksRequestObject) (SearchBooksResponseObject, error)
	// Delete book by id
	// (DELETE /books/{bookID})
	DeleteBookByID(ctx context.Context, request DeleteBookByIDRequestObject) (DeleteBookByIDResponseObject, error)
	// Get book by id
	// (GET /books/{bookID})
	GetBookByID(ctx context.Context, request GetBookByIDRequestObject) (GetBookByIDResponseObject, error)
	// Replace a book by id
	// (PUT /books/{bookID})
	UpdateBook(ctx context.Context, request UpdateBookRequestObject) (UpdateBookResponseObject, error)
	// List documents for a book
	// (GET /books/{bookID}/documents)
	ListBookDocuments(ctx context.Context, request ListBookDocumentsRequestObject) (ListBookDocumentsResponseObject, error)
	// Create a presigned upload URL for a document
	// (POST /books/{bookID}/documents/presign)
	CreateBookDocumentPresign(ctx context.Context, request CreateBookDocumentPresignRequestObject) (CreateBookDocumentPresignResponseObject, error)
	// Delete a document
	// (DELETE /books/{bookID}/documents/{documentID})
	DeleteBookDocumentByID(ctx context.Context, request DeleteBookDocumentByIDRequestObject) (DeleteBookDocumentByIDResponseObject, error)
	// Get document metadata
	// (GET /books/{bookID}/documents/{documentID})
	GetBookDocumentByID(ctx context.Context, request GetBookDocumentByIDRequestObject) (GetBookDocumentByIDResponseObject, error)
	// Confirm document upload and persist metadata
	// (POST /books/{bookID}/documents/{documentID}/complete)
	CompleteBookDocumentUpload(ctx context.Context, request CompleteBookDocumentUploadRequestObject) (CompleteBookDocumentUploadResponseObject, error)
	// Download a document
	// (GET /books/{bookID}/documents/{documentID}/download)
	DownloadBookDocument(ctx context.Context, request DownloadBookDocumentRequestObject) (DownloadBookDocumentResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListBooks operation middleware
func (sh *strictHandler) ListBooks(ctx *fiber.Ctx, params ListBooksParams) error {
	var request ListBooksRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListBooks(ctx.UserContext(), request.(ListBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListBooksResponseObject); ok {
		if err := validResponse.VisitListBooksResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateBook operation middleware
func (sh *strictHandler) CreateBook(ctx *fiber.Ctx) error {
	var request CreateBookRequestObject

	var body CreateBookJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBook(ctx.UserContext(), request.(CreateBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateBookResponseObject); ok {
		if err := validResponse.VisitCreateBookResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchBooks operation middleware
func (sh *strictHandler) SearchBooks(ctx *fiber.Ctx, params SearchBooksParams) error {
	var request SearchBooksRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SearchBooks(ctx.UserContext(), request.(SearchBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchBooks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(SearchBooksResponseObject); ok {
		if err := validResponse.VisitSearchBooksResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBookByID operation middleware
func (sh *strictHandler) DeleteBookByID(ctx *fiber.Ctx, bookID BookID) error {
	var request DeleteBookByIDRequestObject

	request.BookID = bookID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBookByID(ctx.UserContext(), request.(DeleteBookByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBookByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteBookByIDResponseObject); ok {
		if err := validResponse.VisitDeleteBookByIDResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBookByID operation middleware
func (sh *strictHandler) GetBookByID(ctx *fiber.Ctx, bookID BookID) error {
	var request GetBookByIDRequestObject

	request.BookID = bookID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetBookByID(ctx.UserContext(), request.(GetBookByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBookByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetBookByIDResponseObject); ok {
		if err := validResponse.VisitGetBookByIDResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateBook operation middleware
func (sh *strictHandler) UpdateBook(ctx *fiber.Ctx, bookID BookID) error {
	var request UpdateBookRequestObject

	request.BookID = bookID

	var body UpdateBookJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBook(ctx.UserContext(), request.(UpdateBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBook")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateBookResponseObject); ok {
		if err := validResponse.VisitUpdateBookResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListBookDocuments operation middleware
func (sh *strictHandler) ListBookDocuments(ctx *fiber.Ctx, bookID BookID, params ListBookDocumentsParams) error {
	var request ListBookDocumentsRequestObject

	request.BookID = bookID
	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListBookDocuments(ctx.UserContext(), request.(ListBookDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBookDocuments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListBookDocumentsResponseObject); ok {
		if err := validResponse.VisitListBookDocumentsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateBookDocumentPresign operation middleware
func (sh *strictHandler) CreateBookDocumentPresign(ctx *fiber.Ctx, bookID BookID) error {
	var request CreateBookDocumentPresignRequestObject

	request.BookID = bookID

	var body CreateBookDocumentPresignJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBookDocumentPresign(ctx.UserContext(), request.(CreateBookDocumentPresignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBookDocumentPresign")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateBookDocumentPresignResponseObject); ok {
		if err := validResponse.VisitCreateBookDocumentPresignResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBookDocumentByID operation middleware
func (sh *strictHandler) DeleteBookDocumentByID(ctx *fiber.Ctx, bookID BookID, documentID DocumentID) error {
	var request DeleteBookDocumentByIDRequestObject

	request.BookID = bookID
	request.DocumentID = documentID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBookDocumentByID(ctx.UserContext(), request.(DeleteBookDocumentByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBookDocumentByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteBookDocumentByIDResponseObject); ok {
		if err := validResponse.VisitDeleteBookDocumentByIDResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBookDocumentByID operation middleware
func (sh *strictHandler) GetBookDocumentByID(ctx *fiber.Ctx, bookID BookID, documentID DocumentID) error {
	var request GetBookDocumentByIDRequestObject

	request.BookID = bookID
	request.DocumentID = documentID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetBookDocumentByID(ctx.UserContext(), request.(GetBookDocumentByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBookDocumentByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetBookDocumentByIDResponseObject); ok {
		if err := validResponse.VisitGetBookDocumentByIDResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CompleteBookDocumentUpload operation middleware
func (sh *strictHandler) CompleteBookDocumentUpload(ctx *fiber.Ctx, bookID BookID, documentID DocumentID) error {
	var request CompleteBookDocumentUploadRequestObject

	request.BookID = bookID
	request.DocumentID = documentID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteBookDocumentUpload(ctx.UserContext(), request.(CompleteBookDocumentUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteBookDocumentUpload")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CompleteBookDocumentUploadResponseObject); ok {
		if err := validResponse.VisitCompleteBookDocumentUploadResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DownloadBookDocument operation middleware
func (sh *strictHandler) DownloadBookDocument(ctx *fiber.Ctx, bookID BookID, documentID DocumentID) error {
	var request DownloadBookDocumentRequestObject

	request.BookID = bookID
	request.DocumentID = documentID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadBookDocument(ctx.UserContext(), request.(DownloadBookDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadBookDocument")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DownloadBookDocumentResponseObject); ok {
		if err := validResponse.VisitDownloadBookDocumentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
