// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID            int64              `json:"id"`
	UserID        string             `json:"user_id"`
	Title         string             `json:"title"`
	Author        string             `json:"author"`
	PublishedYear int32              `json:"published_year"`
	Isbn          string             `json:"isbn"`
	Genre         *string            `json:"genre"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID          int64              `json:"id"`
	BookID      *int64             `json:"book_id"`
	Filename    string             `json:"filename"`
	ObjectKey   string             `json:"object_key"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Status      string             `json:"status"`
	Checksum    string             `json:"checksum"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
