// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const countBooks = `-- name: CountBooks :one
SELECT count(*)::bigint AS total
FROM books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBooks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countBooksBySearch = `-- name: CountBooksBySearch :one
SELECT count(*)::bigint AS total
FROM books
WHERE title ILIKE '%' || $1 || '%' OR author ILIKE '%' || $1 || '%'
`

func (q *Queries) CountBooksBySearch(ctx context.Context, dollar_1 *string) (int64, error) {
	row := q.db.QueryRow(ctx, countBooksBySearch, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDocumentsByBook = `-- name: CountDocumentsByBook :one
SELECT count(*)::bigint AS total
FROM documents
WHERE book_id = $1
`

func (q *Queries) CountDocumentsByBook(ctx context.Context, bookID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByBook, bookID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
  title,
  author,
  published_year,
  isbn,
  genre
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, title, author, published_year, isbn, genre, created_at
`

type CreateBookParams struct {
	Title         string  `json:"title"`
	Author        string  `json:"author"`
	PublishedYear int32   `json:"published_year"`
	Isbn          string  `json:"isbn"`
	Genre         *string `json:"genre"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.PublishedYear,
		arg.Isbn,
		arg.Genre,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedYear,
		&i.Isbn,
		&i.Genre,
		&i.CreatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
  book_id,
  filename,
  object_key,
  content_type,
  size_bytes,
  status,
  checksum
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, book_id, filename, object_key, content_type, size_bytes, status, checksum, created_at, updated_at
`

type CreateDocumentParams struct {
	BookID      *int64 `json:"book_id"`
	Filename    string `json:"filename"`
	ObjectKey   string `json:"object_key"`
	ContentType string `json:"content_type"`
	SizeBytes   int32  `json:"size_bytes"`
	Status      string `json:"status"`
	Checksum    string `json:"checksum"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.BookID,
		arg.Filename,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Checksum,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :execrows
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, published_year, isbn, genre, created_at
FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedYear,
		&i.Isbn,
		&i.Genre,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, book_id, filename, object_key, content_type, size_bytes, status, checksum, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByObjectKey = `-- name: GetDocumentByObjectKey :one
SELECT id, book_id, filename, object_key, content_type, size_bytes, status, checksum, created_at, updated_at
FROM documents
WHERE object_key = $1
`

func (q *Queries) GetDocumentByObjectKey(ctx context.Context, objectKey string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByObjectKey, objectKey)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, published_year, isbn, genre, created_at
FROM books
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.PublishedYear,
			&i.Isbn,
			&i.Genre,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByBook = `-- name: ListDocumentsByBook :many
SELECT id, book_id, filename, object_key, content_type, size_bytes, status, checksum, created_at, updated_at
FROM documents
WHERE book_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListDocumentsByBookParams struct {
	BookID *int64 `json:"book_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByBook(ctx context.Context, arg ListDocumentsByBookParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByBook, arg.BookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Filename,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, title, author, published_year, isbn, genre, created_at
FROM books
WHERE title ILIKE '%' || $1 || '%' OR author ILIKE '%' || $1 || '%'
ORDER BY id
LIMIT $2 OFFSET $3
`

type SearchBooksParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.PublishedYear,
			&i.Isbn,
			&i.Genre,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2,
    author = $3,
    published_year = $4,
    isbn = $5,
    genre = $6
WHERE id = $1
RETURNING id, title, author, published_year, isbn, genre, created_at
`

type UpdateBookParams struct {
	ID            int64   `json:"id"`
	Title         string  `json:"title"`
	Author        string  `json:"author"`
	PublishedYear int32   `json:"published_year"`
	Isbn          string  `json:"isbn"`
	Genre         *string `json:"genre"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.PublishedYear,
		arg.Isbn,
		arg.Genre,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedYear,
		&i.Isbn,
		&i.Genre,
		&i.CreatedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, book_id, filename, object_key, content_type, size_bytes, status, checksum, created_at, updated_at
`

type UpdateDocumentStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.ID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFullDocument = `-- name: UpdateFullDocument :one
UPDATE documents
SET filename = $2,
    object_key = $3,
    content_type = $4,
    size_bytes = $5,
    status = $6,
    checksum = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, book_id, filename, object_key, content_type, size_bytes, status, checksum, created_at, updated_at
`

type UpdateFullDocumentParams struct {
	ID          int64  `json:"id"`
	Filename    string `json:"filename"`
	ObjectKey   string `json:"object_key"`
	ContentType string `json:"content_type"`
	SizeBytes   int32  `json:"size_bytes"`
	Status      string `json:"status"`
	Checksum    string `json:"checksum"`
}

func (q *Queries) UpdateFullDocument(ctx context.Context, arg UpdateFullDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateFullDocument,
		arg.ID,
		arg.Filename,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Checksum,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
