// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const checkBookOwnership = `-- name: CheckBookOwnership :one
select id
from books
where id = $1 and user_id = $2
`

type CheckBookOwnershipParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CheckBookOwnership(ctx context.Context, arg CheckBookOwnershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkBookOwnership, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const checkDocumentOwnership = `-- name: CheckDocumentOwnership :one
select d.id
from documents d
join books b on d.book_id = b.id
where d.id = $1 and b.user_id = $2
`

type CheckDocumentOwnershipParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CheckDocumentOwnership(ctx context.Context, arg CheckDocumentOwnershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkDocumentOwnership, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const countBooks = `-- name: CountBooks :one
select count(*)::bigint as total
from books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBooks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countBooksBySearch = `-- name: CountBooksBySearch :one
select count(*)::bigint as total
from books
where title ilike '%' || $1 || '%' or author ilike '%' || $1 || '%'
`

func (q *Queries) CountBooksBySearch(ctx context.Context, dollar_1 *string) (int64, error) {
	row := q.db.QueryRow(ctx, countBooksBySearch, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDocumentsByBook = `-- name: CountDocumentsByBook :one
select count(*)::bigint as total
from documents
where book_id = $1
`

func (q *Queries) CountDocumentsByBook(ctx context.Context, bookID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByBook, bookID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBook = `-- name: CreateBook :one
insert into books (
  user_id,
  title,
  author,
  published_year,
  isbn,
  genre
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
returning id,
          user_id,
          title,
          author,
          published_year,
          isbn,
          genre,
          created_at
`

type CreateBookParams struct {
	UserID        string  `json:"user_id"`
	Title         string  `json:"title"`
	Author        string  `json:"author"`
	PublishedYear int32   `json:"published_year"`
	Isbn          string  `json:"isbn"`
	Genre         *string `json:"genre"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.UserID,
		arg.Title,
		arg.Author,
		arg.PublishedYear,
		arg.Isbn,
		arg.Genre,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Author,
		&i.PublishedYear,
		&i.Isbn,
		&i.Genre,
		&i.CreatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
insert into documents as d
(
  book_id,
  filename,
  object_key,
  content_type,
  size_bytes,
  status,
  checksum
)
select $1, $3, $4, $5, $6, $7, $8
from books as b
where b.id = $1
  and b.user_id = $2
returning d.id,
          d.book_id,
          d.filename,
          d.object_key,
          d.content_type,
          d.size_bytes,
          d.status,
          d.checksum,
          d.created_at,
          d.updated_at
`

type CreateDocumentParams struct {
	BookID      *int64 `json:"book_id"`
	UserID      string `json:"user_id"`
	Filename    string `json:"filename"`
	ObjectKey   string `json:"object_key"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Status      string `json:"status"`
	Checksum    string `json:"checksum"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.BookID,
		arg.UserID,
		arg.Filename,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Checksum,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :execrows
delete from books
where id = $1 and user_id = $2
`

type DeleteBookParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteBook(ctx context.Context, arg DeleteBookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBook, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDocument = `-- name: DeleteDocument :execrows
delete from documents
using books
where documents.id = $1
  and documents.book_id = $2
  and documents.book_id = books.id
  and books.user_id = $3
`

type DeleteDocumentParams struct {
	ID     int64  `json:"id"`
	BookID *int64 `json:"book_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.BookID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDocumentsByBook = `-- name: DeleteDocumentsByBook :execrows
delete from documents as d
using books as b
where d.book_id = b.id
  and d.book_id = $1
  and b.user_id = $2
`

type DeleteDocumentsByBookParams struct {
	BookID *int64 `json:"book_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDocumentsByBook(ctx context.Context, arg DeleteDocumentsByBookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocumentsByBook, arg.BookID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBook = `-- name: GetBook :one
select id,
        user_id,
        title,
        author,
        published_year,
        isbn,
        genre,
        created_at
from books
where id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Author,
		&i.PublishedYear,
		&i.Isbn,
		&i.Genre,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
select id,
       book_id,
       filename,
       object_key,
       content_type,
       size_bytes,
       status,
       checksum,
       created_at,
       updated_at
from documents
where id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByObjectKey = `-- name: GetDocumentByObjectKey :one
select id,
       book_id,
       filename,
       object_key,
       content_type,
       size_bytes,
       status,
       checksum,
       created_at,
       updated_at
from documents
where object_key = $1
`

func (q *Queries) GetDocumentByObjectKey(ctx context.Context, objectKey string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByObjectKey, objectKey)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrUpdateDocument = `-- name: InsertOrUpdateDocument :one
insert into documents 
(
  book_id,
  filename,
  object_key,
  content_type,
  size_bytes,
  status,
  checksum
) 
select $1, $3, $4, $5, $6, $7, $8
from books as b
where b.id = $1
  and b.user_id = $2
on conflict (object_key) do update
set book_id = excluded.book_id,
    filename = excluded.filename,
    content_type = excluded.content_type,
    size_bytes = excluded.size_bytes,
    status = excluded.status,
    checksum = excluded.checksum,
    updated_at = now()
returning id,
          book_id,
          filename,
          object_key,
          content_type,
          size_bytes,
          status,
          checksum,
          created_at,
          updated_at
`

type InsertOrUpdateDocumentParams struct {
	BookID      *int64 `json:"book_id"`
	UserID      string `json:"user_id"`
	Filename    string `json:"filename"`
	ObjectKey   string `json:"object_key"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Status      string `json:"status"`
	Checksum    string `json:"checksum"`
}

func (q *Queries) InsertOrUpdateDocument(ctx context.Context, arg InsertOrUpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertOrUpdateDocument,
		arg.BookID,
		arg.UserID,
		arg.Filename,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Checksum,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
select id,
       user_id,
       title,
       author,
       published_year,
       isbn,
       genre,
       created_at
from books
order by id
limit $1 offset $2
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Author,
			&i.PublishedYear,
			&i.Isbn,
			&i.Genre,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByBook = `-- name: ListDocumentsByBook :many
select id,
       book_id,
       filename,
       object_key,
       content_type,
       size_bytes,
       status,
       checksum,
       created_at,
       updated_at
from documents
where book_id = $1
order by id
limit $2 offset $3
`

type ListDocumentsByBookParams struct {
	BookID *int64 `json:"book_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByBook(ctx context.Context, arg ListDocumentsByBookParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByBook, arg.BookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Filename,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
select id,
       user_id,
       title,
       author,
       published_year,
       isbn,
       genre,
       created_at
from books
where title ilike '%' || $1 || '%' or author ilike '%' || $1 || '%'
order by id
limit $2 offset $3
`

type SearchBooksParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Author,
			&i.PublishedYear,
			&i.Isbn,
			&i.Genre,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
update books
set title = $3,
    author = $4,
    published_year = $5,
    isbn = $6,
    genre = $7
where id = $1 and user_id = $2
returning id,
          user_id,
          title,
          author,
          published_year,
          isbn,
          genre,
          created_at
`

type UpdateBookParams struct {
	ID            int64   `json:"id"`
	UserID        string  `json:"user_id"`
	Title         string  `json:"title"`
	Author        string  `json:"author"`
	PublishedYear int32   `json:"published_year"`
	Isbn          string  `json:"isbn"`
	Genre         *string `json:"genre"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Author,
		arg.PublishedYear,
		arg.Isbn,
		arg.Genre,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Author,
		&i.PublishedYear,
		&i.Isbn,
		&i.Genre,
		&i.CreatedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
update documents as d
set status = $3,
    updated_at = now()
from books as b
where d.id = $1
  and d.book_id = b.id
  and b.user_id = $2
returning d.id,
          d.book_id,
          d.filename,
          d.object_key,
          d.content_type,
          d.size_bytes,
          d.status,
          d.checksum,
          d.created_at,
          d.updated_at
`

type UpdateDocumentStatusParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.ID, arg.UserID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFullDocument = `-- name: UpdateFullDocument :one
update documents as d
set filename = $3,
    content_type = $4,
    size_bytes = $5,
    status = $6,
    checksum = $7,
    updated_at = now()
from books as b
where d.id = $1
  and d.book_id = b.id
  and b.user_id = $2
returning d.id,
          d.book_id,
          d.filename,
          d.object_key,
          d.content_type,
          d.size_bytes,
          d.status,
          d.checksum,
          d.created_at,
          d.updated_at
`

type UpdateFullDocumentParams struct {
	ID          int64  `json:"id"`
	UserID      string `json:"user_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Status      string `json:"status"`
	Checksum    string `json:"checksum"`
}

func (q *Queries) UpdateFullDocument(ctx context.Context, arg UpdateFullDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateFullDocument,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Checksum,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Filename,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
