// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBookData, CreateBookErrors, CreateBookResponses, DeleteBookByIdData, DeleteBookByIdErrors, DeleteBookByIdResponses, GetBookByIdData, GetBookByIdErrors, GetBookByIdResponses, ListBooksData, ListBooksResponses, SearchBooksData, SearchBooksResponses, UpdateBookData, UpdateBookErrors, UpdateBookResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List books
 */
export const listBooks = <ThrowOnError extends boolean = false>(options?: Options<ListBooksData, ThrowOnError>) => (options?.client ?? client).get<ListBooksResponses, unknown, ThrowOnError>({ url: '/books', ...options });

/**
 * Create a new book
 */
export const createBook = <ThrowOnError extends boolean = false>(options: Options<CreateBookData, ThrowOnError>) => (options.client ?? client).post<CreateBookResponses, CreateBookErrors, ThrowOnError>({
    url: '/books',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Search books by title or author
 */
export const searchBooks = <ThrowOnError extends boolean = false>(options: Options<SearchBooksData, ThrowOnError>) => (options.client ?? client).get<SearchBooksResponses, unknown, ThrowOnError>({ url: '/books/search', ...options });

/**
 * Delete book by id
 */
export const deleteBookById = <ThrowOnError extends boolean = false>(options: Options<DeleteBookByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteBookByIdResponses, DeleteBookByIdErrors, ThrowOnError>({ url: '/books/{bookID}', ...options });

/**
 * Get book by id
 */
export const getBookById = <ThrowOnError extends boolean = false>(options: Options<GetBookByIdData, ThrowOnError>) => (options.client ?? client).get<GetBookByIdResponses, GetBookByIdErrors, ThrowOnError>({ url: '/books/{bookID}', ...options });

/**
 * Replace a book by id
 */
export const updateBook = <ThrowOnError extends boolean = false>(options: Options<UpdateBookData, ThrowOnError>) => (options.client ?? client).put<UpdateBookResponses, UpdateBookErrors, ThrowOnError>({
    url: '/books/{bookID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
