// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Book = {
    id: number;
    title: string;
    author: string;
    publishedYear: string;
    isbn: string;
    genre?: string;
};

export type BookCreate = {
    title: string;
    author: string;
    publishedYear: string;
    isbn: string;
    genre?: string;
};

export type BookUpdate = {
    title: string;
    author: string;
    publishedYear: string;
    isbn: string;
    genre?: string;
};

export type BookList = {
    items: Array<Book>;
    total: number;
};

export type Problem = {
    type?: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
};

/**
 * id of the book
 */
export type BookId = number;

export type ListBooksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/books';
};

export type ListBooksResponses = {
    /**
     * Successful response
     */
    200: BookList;
};

export type ListBooksResponse = ListBooksResponses[keyof ListBooksResponses];

export type CreateBookData = {
    body: BookCreate;
    path?: never;
    query?: never;
    url: '/books';
};

export type CreateBookErrors = {
    /**
     * Validation error
     */
    422: Problem;
};

export type CreateBookError = CreateBookErrors[keyof CreateBookErrors];

export type CreateBookResponses = {
    /**
     * Created
     */
    201: Book;
};

export type CreateBookResponse = CreateBookResponses[keyof CreateBookResponses];

export type SearchBooksData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
        offset?: number;
    };
    url: '/books/search';
};

export type SearchBooksResponses = {
    /**
     * Successful response
     */
    200: BookList;
};

export type SearchBooksResponse = SearchBooksResponses[keyof SearchBooksResponses];

export type DeleteBookByIdData = {
    body?: never;
    path: {
        /**
         * id of the book
         */
        bookID: number;
    };
    query?: never;
    url: '/books/{bookID}';
};

export type DeleteBookByIdErrors = {
    /**
     * Book not found
     */
    404: Problem;
};

export type DeleteBookByIdError = DeleteBookByIdErrors[keyof DeleteBookByIdErrors];

export type DeleteBookByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteBookByIdResponse = DeleteBookByIdResponses[keyof DeleteBookByIdResponses];

export type GetBookByIdData = {
    body?: never;
    path: {
        /**
         * id of the book
         */
        bookID: number;
    };
    query?: never;
    url: '/books/{bookID}';
};

export type GetBookByIdErrors = {
    /**
     * Book not found
     */
    404: Problem;
};

export type GetBookByIdError = GetBookByIdErrors[keyof GetBookByIdErrors];

export type GetBookByIdResponses = {
    /**
     * Successful response
     */
    200: Book;
};

export type GetBookByIdResponse = GetBookByIdResponses[keyof GetBookByIdResponses];

export type UpdateBookData = {
    body: BookUpdate;
    path: {
        /**
         * id of the book
         */
        bookID: number;
    };
    query?: never;
    url: '/books/{bookID}';
};

export type UpdateBookErrors = {
    /**
     * Book not found
     */
    404: Problem;
    /**
     * Validation error
     */
    422: Problem;
};

export type UpdateBookError = UpdateBookErrors[keyof UpdateBookErrors];

export type UpdateBookResponses = {
    /**
     * Updated
     */
    200: Book;
};

export type UpdateBookResponse = UpdateBookResponses[keyof UpdateBookResponses];
