// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBook = z.object({
    id: z.coerce.bigint(),
    title: z.string(),
    author: z.string(),
    publishedYear: z.string(),
    isbn: z.string(),
    genre: z.optional(z.string())
});

export const zBookCreate = z.object({
    title: z.string(),
    author: z.string(),
    publishedYear: z.string(),
    isbn: z.string(),
    genre: z.optional(z.string())
});

export const zBookUpdate = z.object({
    title: z.string(),
    author: z.string(),
    publishedYear: z.string(),
    isbn: z.string(),
    genre: z.optional(z.string())
});

export const zBookList = z.object({
    items: z.array(zBook),
    total: z.coerce.bigint()
});

export const zProblem = z.object({
    type: z.optional(z.url()),
    title: z.string(),
    status: z.int(),
    detail: z.optional(z.string()),
    instance: z.optional(z.string())
});

/**
 * id of the book
 */
export const zBookId = z.coerce.bigint();

export const zListBooksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int().gte(1).lte(100)).default(20),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * Successful response
 */
export const zListBooksResponse = zBookList;

export const zCreateBookData = z.object({
    body: zBookCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateBookResponse = zBook;

export const zSearchBooksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        q: z.string(),
        limit: z.optional(z.int().gte(1).lte(100)).default(20),
        offset: z.optional(z.int().gte(0)).default(0)
    })
});

/**
 * Successful response
 */
export const zSearchBooksResponse = zBookList;

export const zDeleteBookByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bookID: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * Deleted
 */
export const zDeleteBookByIdResponse = z.void();

export const zGetBookByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bookID: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zGetBookByIdResponse = zBook;

export const zUpdateBookData = z.object({
    body: zBookUpdate,
    path: z.object({
        bookID: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * Updated
 */
export const zUpdateBookResponse = zBook;
