openapi: 3.0.0
info:
  title: Book API
  version: 0.0.1
servers:
  - url: /
    description: Default server
security: []
tags:
  - name: books
    description: Manage books
  - name: documents
    description: upload book documents
paths:
  /books:
    get:
      operationId: listBooks
      tags:
        - books
      summary: List books
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            default: 20
            minimum: 1
            maximum: 100
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
    post:
      security:
        - BearerAuth: []
      operationId: createBook
      tags:
        - books
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /books/search:
    get:
      operationId: searchBooks
      tags:
        - books
      summary: Search books by title or author
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            default: 20
            minimum: 1
            maximum: 100
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
  /books/{bookID}:
    get:
      operationId: getBookByID
      tags:
        - books
      summary: Get book by id
      parameters:
        - $ref: '#/components/parameters/BookID'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
    put:
      security:
        - BearerAuth: []
      operationId: updateBook
      tags:
        - books
      summary: Replace a book by id
      parameters:
        - $ref: '#/components/parameters/BookID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookUpdate'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      security:
        - BearerAuth: []
      operationId: deleteBookByID
      tags:
        - books
      summary: Delete book by id
      parameters:
        - $ref: '#/components/parameters/BookID'
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /books/{bookID}/documents:
    get:
      operationId: listBookDocuments
      tags:
        - documents
      summary: List documents for a book
      parameters:
        - $ref: '#/components/parameters/BookID'
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            default: 20
            minimum: 1
            maximum: 100
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentList'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /books/{bookID}/documents/presign:
    post:
      security:
        - BearerAuth: []
      operationId: createBookDocumentPresign
      tags:
        - documents
      summary: Create a presigned upload URL for a document
      description: Only authenticated uploaders can request a presigned URL.
      parameters:
        - $ref: '#/components/parameters/BookID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentUploadRequest'
      responses:
        '201':
          description: Presigned upload created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentPresignResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /books/{bookID}/documents/{documentID}:
    get:
      operationId: getBookDocumentByID
      tags:
        - documents
      summary: Get document metadata
      parameters:
        - $ref: '#/components/parameters/BookID'
        - $ref: '#/components/parameters/DocumentID'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      security:
        - BearerAuth: []
      operationId: deleteBookDocumentByID
      tags:
        - documents
      summary: Delete a document
      description: Only the uploader or an admin can delete documents.
      parameters:
        - $ref: '#/components/parameters/BookID'
        - $ref: '#/components/parameters/DocumentID'
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /books/{bookID}/documents/{documentID}/complete:
    post:
      security:
        - BearerAuth: []
      operationId: completeBookDocumentUpload
      tags:
        - documents
      summary: Confirm document upload and persist metadata
      description: Completes the upload after the file is stored in R2.
      parameters:
        - $ref: '#/components/parameters/BookID'
        - $ref: '#/components/parameters/DocumentID'
      responses:
        '200':
          description: Upload confirmed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /books/{bookID}/documents/{documentID}/download:
    get:
      operationId: downloadBookDocument
      tags:
        - documents
      summary: Download a document
      description: Redirects to the public R2 object URL.
      parameters:
        - $ref: '#/components/parameters/BookID'
        - $ref: '#/components/parameters/DocumentID'
      responses:
        '302':
          description: Redirect to public download URL
          headers:
            Location:
              description: Public R2 download URL
              schema:
                type: string
                format: uri
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
      bearerFormat: JWT
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
        - publishedYear
        - isbn
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: string
        isbn:
          type: string
        genre:
          type: string
    BookList:
      type: object
      required:
        - items
        - total
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Book'
        total:
          type: integer
          format: int64
    BookCreate:
      type: object
      required:
        - title
        - author
        - publishedYear
        - isbn
      properties:
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: string
        isbn:
          type: string
        genre:
          type: string
    Problem:
      type: object
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
    BookUpdate:
      type: object
      required:
        - title
        - author
        - publishedYear
        - isbn
      properties:
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: string
        isbn:
          type: string
        genre:
          type: string
    ContentType:
      type: string
      enum:
        - application/pdf
        - application/epub+zip
    UploadStatus:
      type: string
      enum:
        - pending
        - uploaded
        - processing
        - ready
        - failed
    Document:
      type: object
      required:
        - id
        - bookID
        - filename
        - contentType
        - sizeBytes
        - status
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int64
        bookID:
          type: integer
          format: int64
        filename:
          type: string
        contentType:
          $ref: '#/components/schemas/ContentType'
        sizeBytes:
          type: integer
          format: int64
        status:
          $ref: '#/components/schemas/UploadStatus'
        objectKey:
          type: string
        checksumSha256Hex:
          type: string
          description: SHA-256 checksum as 64 lowercase hex chars
          pattern: ^[0-9a-f]{64}$
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    DocumentList:
      type: object
      required:
        - items
        - total
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Document'
        total:
          type: integer
          format: int64
    DocumentUploadRequest:
      type: object
      required:
        - filename
        - contentType
        - sizeBytes
        - checksumSha256Hex
      properties:
        filename:
          type: string
        contentType:
          $ref: '#/components/schemas/ContentType'
        sizeBytes:
          type: integer
          format: int64
          minimum: 1
          maximum: 20971520
        checksumSha256Hex:
          type: string
          description: SHA-256 checksum as 64 lowercase hex chars
          pattern: ^[0-9a-f]{64}$
        metadata:
          type: object
          additionalProperties:
            type: string
    DocumentPresignResponse:
      type: object
      required:
        - document
        - uploadUrl
        - uploadMethod
        - expiresAt
      properties:
        document:
          $ref: '#/components/schemas/Document'
        uploadUrl:
          type: string
          format: uri
        uploadMethod:
          type: string
          enum:
            - PUT
        expiresAt:
          type: string
          format: date-time
  parameters:
    BookID:
      name: bookID
      in: path
      required: true
      description: id of the book
      schema:
        type: integer
        format: int64
    DocumentID:
      name: documentID
      in: path
      required: true
      description: id of the document
      schema:
        type: integer
        format: int64
